name: Release Packages

on:
  workflow_dispatch:
    inputs:
      pre:
        description: "Is this a NEW pre-release?"
        required: false
        default: false
        type: boolean
      level:
        description: "Release level"
        required: true
        default: "patch"
        type: choice
        options:
          - patch
          - minor
          - major
          - preup

jobs:
  release-packages:
    name: Release packages sequentially
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      id-token: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Node.js
        uses: jdx/mise-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          install_args: "node pnpm"
          cache: true

      - uses: pnpm/action-setup@v4

      - name: Setup .npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Release shared
        run: |
          if [ "${{ github.event.inputs.pre }}" == "true" ]; then
            pnpm p:shared release --level ${{ github.event.inputs.level }} --pre
          else
            pnpm p:shared release --level ${{ github.event.inputs.level }}
          fi

      - name: Get package version
        id: get-version
        run: |
          echo "package-version=$(node -p \"require('./packages/shared/package.json').version\")" >> $GITHUB_OUTPUT

      - name: Release dependent packages
        run: |
          for pkg in reactivity transformer runtime plugin components core; do
            pnpm p:${pkg} release --level fix --release-version ${{ steps.get-version.outputs.package-version }} -k create-release-branch,build
          done

      - name: Create Pull Request
        run: |
          gh pr create \
            --title "Release v${{ steps.get-version.outputs.package-version }}" \
            --body "Release v${{ steps.get-version.outputs.package-version }} This PR was automatically generated by the release workflow." \
            --base main \
            --reviewer takuma-ru \
            --label ":rocket: release"

      - name: Create GitHub Release
        id: create-release
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.get-version.outputs.package-version }}
          prerelease: ${{ contains(steps.get-version.outputs.package-version, '-beta') }}
